apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

helmCharts:
  - name: ingress-nginx
    includeCRDs: true
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx

resources:
  - namespace.yaml
