apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
  - name: cert-manager
    includeCRDs: true
    releaseName: jetstack/cert-manager
    repo: https://charts.external-secrets.io

resources:
  - namespace.yaml
